; This file is stored in UTF-8 encoding
[Info]
Name = ASI One Ai Sidebar
Author = UltraTechDz
Author URL = https://asi1.ai
Version = 1

[Window Image]
file = logo.png

[Start Page]
background = logo.png
position = center center
title text color = #FFFFFF
title text shadow = #000000

[Web UI Pages]
background = logo.png
position = center center
